export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE'

export const REFRESH_REVIEWS_REQUEST = 'REFRESH_REVIEWS_REQUEST'
export const REFRESH_REVIEWS_SUCCESS = 'REFRESH_REVIEWS_SUCCESS'
export const REFRESH_REVIEWS_FAILURE = 'REFRESH_REVIEWS_FAILURE'
